### PR TITLE
Update Location.xml

### PR DESCRIPTION
**Pull request by mikkelbu**
Change code blocks to inline code to make the paragraph read nicer.

### CODE REVIEW

**Comment by mikkelbu** [comment]
Looking at this PR I think that the PR should be against `dotnet:master` and not `dotnet:live`. I did not specify this when creating the PR, so I guess that `dotnet:live` is the default branch?

**Comment by BillWagner** [comment]
Thanks for pointing out the base branch @mikkelbu It should target `master`.  cc @dend PRs using the "edit" button have targeted the `live` branch in API reference a couple times now. Could it be an OPS config thing?

**Comment by mairaw** [comment]
I've opened a PR to fix that @BillWagner

**Comment by mikkelbu** [comment]
@BillWagner I've supplied a PR for the dotnet/Roslyn repo.

**Comment by BillWagner** [comment]
closing. The changes are in dotnet/roslyn#26641

**Pull request closed without merging**
