### PR TITLE
disable PR comments

### PR DESCRIPTION
**Pull request by mairaw**
This should take care of the automated comments on every commit in PRs

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/mairaw/roslyn-api-docs/blob/mairaw-patch-1/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C4%5C99429eda-4fb5-c2c3-4fb3-e5c6d51ccc52%5CPullRequest%5C201804041731297365-39%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rL2J2ohc9V6eHkLZSbDNbsv0Q0qzmSMGM6j9rTk8DoY%3D&st=2018-04-04T17%3A29%3A35Z&se=2018-05-05T17%3A34%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by BillWagner** [comment]
closing and reopening to trigger CLA status.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/mairaw/roslyn-api-docs/blob/mairaw-patch-1/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C4%5C99429eda-4fb5-c2c3-4fb3-e5c6d51ccc52%5CPullRequest%5C201804041740096160-39%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BjQ%2BdOex2v5d%2BUcesb9k0lAq4IY%2FcTH5ODk0bEyxLTI%3D&st=2018-04-04T17%3A38%3A17Z&se=2018-05-05T17%3A43%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mairaw** [comment]
@BillWagner I removed the need for the PR to have the latest from master as well in the settings.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/mairaw/roslyn-api-docs/blob/mairaw-patch-1/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C4%5C99429eda-4fb5-c2c3-4fb3-e5c6d51ccc52%5CPullRequest%5C201804041742338192-39%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gSdZqqplN%2Fpnx%2Bvgje1cc54MRUc%2B8xwYJO1BDVzqpnY%3D&st=2018-04-04T17%3A41%3A31Z&se=2018-05-05T17%3A46%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
